Repository ChrisNavoczynski/Dog-Date, pull requests merged in 2021-12, with the labels that each got.

#82 update geolocation
  app/src/main/java/com/example/dog_date/ClickProfile.java
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/OwnerProfilePage.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/java/com/example/dog_date/Upload.java
  app/src/main/java/com/example/dog_date/ViewModels/OwnerProfileViewModel.java
  app/src/main/java/com/example/dog_date/models/OwnerProfileModel.java
  app/src/main/res/layout/owner_profile_page.xml
Labels: enhancement

#83 Code cov kevin
  app/build.gradle
  app/src/androidTest/java/com/example/dog_date/LogIn_SignUpTest.java
  app/src/androidTest/java/com/example/dog_date/MainActivityTest.java
  app/src/androidTest/java/com/example/dog_date/SignUpActivityTest.java
Labels: code, testing

#85 Removed commented out code
  app/src/androidTest/java/com/example/dog_date/LogInActivityTest.java
  app/src/androidTest/java/com/example/dog_date/MainActivityTest.java
  app/src/androidTest/java/com/example/dog_date/SignUpActivityTest.java
Labels: code

#87 Connect and Clean up
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/dog_date/BaseActivity.java
  app/src/main/java/com/example/dog_date/ChatActivity.java
  app/src/main/java/com/example/dog_date/ClickProfile.java
  app/src/main/java/com/example/dog_date/CurrentUserActivity.java
  app/src/main/java/com/example/dog_date/DogProfile.java
  app/src/main/java/com/example/dog_date/DogProfilePage.java
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/Login_SignupActivity.java
  app/src/main/java/com/example/dog_date/MainActivity.java
  app/src/main/java/com/example/dog_date/Match/MatchAdapter.java
  app/src/main/java/com/example/dog_date/Match/MatchViewHolders.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/OwnerProfilePage.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/java/com/example/dog_date/ViewModels/DogProfileViewModel.java
  app/src/main/java/com/example/dog_date/adapters/RecentConversationsAdapter.java
  app/src/main/java/com/example/dog_date/arrayAdapter.java
  app/src/main/res/layout/activity_current_user.xml
  app/src/main/res/layout/activity_login_signup.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/swipe_activity.xml
Labels: code

#88 Clean Up Part 2
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/dog_date/CurrentUserActivity.java
Labels: bug, code

#89 Final connectivity issues
  app/src/main/java/com/example/dog_date/CurrentUserActivity.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/res/layout/activity_current_user.xml
  app/src/main/res/layout/swipe_activity.xml
Labels: bug, code

#90 Sign Up and Log In Testing
  .idea/shelf/Uncommitted_changes_before_Checkout_at_12_5_2021_6_05_PM_[Default_Changelist]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_12_5_2021_6_05_PM__Default_Changelist_.xml
  app/build.gradle
  app/src/androidTest/java/com/example/dog_date/LogInActivityTest.java
  app/src/androidTest/java/com/example/dog_date/SignUpActivityTest.java
Labels: in process

#91 Jjh test2
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/com/example/dog_date/OwnerProfileTest.java
  app/src/androidTest/java/com/example/dog_date/PreferenceOwnerTest.java
  app/src/androidTest/java/com/example/dog_date/PreferenceTest.java
  app/src/main/java/com/example/dog_date/ClickProfile.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/Preference.java
  app/src/main/java/com/example/dog_date/Preference_owner.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/res/layout/preference.xml
  app/src/main/res/layout/preference_owner.xml
Labels: testing
