Repository ChrisNavoczynski/Dog-Date, pull requests merged in 2021-10, with the labels that each got.

#10 Testing
  .idea/gradle.xml
  .idea/runConfigurations.xml
  app/src/androidTest/java/com/example/dog_date/DogProfileTest.java
  app/src/androidTest/java/com/example/dog_date/MainActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/DogProfile.java
  app/src/main/java/com/example/dog_date/DoggyProfile.java
  app/src/main/java/com/example/dog_date/MainActivity.java
  app/src/main/res/layout/doggy_profile.xml
  app/src/main/res/layout/preference.xml
  app/src/main/res/layout/profile_dog.xml
  app/src/main/res/values/strings.xml
Labels: code, testing

#18 add upload function, change state spinner to breeds spinner, and change checkBox to radio button
  .idea/misc.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2021_10_18_11_20_[Default_Changelist]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2021_10_18_11_20__Default_Changelist_.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/DogProfile.java
  app/src/main/java/com/example/dog_date/Preference.java
  app/src/main/java/com/example/dog_date/Upload.java
  app/src/main/res/layout/preference.xml
  app/src/main/res/layout/preference_owner.xml
  app/src/main/res/layout/profile_dog.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, testing

#32 fix conflicts and add add swipe activity
  .idea/shelf/Uncommitted_changes_before_Checkout_at_10_19_2021_5_58_PM_[Default_Changelist]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_10_19_2021_5_58_PM__Default_Changelist_.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/java/com/example/dog_date/arrayAdapter.java
  app/src/main/res/layout/item.xml
  app/src/main/res/layout/swipe_activity.xml
Labels: code, draft
