Repository ChrisNavoczynski/Dog-Date, pull requests merged in 2021-11, with the labels that each got.

#37 Password validation
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/SignUpActivity.java
Labels: enhancement, code

#41 chat function
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/java/com/example/dog_date/chat/ChatAdapter.java
  app/src/main/java/com/example/dog_date/chat/ChatObject.java
  app/src/main/java/com/example/dog_date/chat/ChatViewHolders.java
  app/src/main/java/com/example/dog_date/chat/MessageActivity.java
  app/src/main/res/layout/activity_message.xml
  app/src/main/res/layout/chat_item.xml
Labels: code

#50 Log in and Sign up update
  app/build.gradle
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/SignUpActivity.java
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/values/strings.xml
Labels: code

#52 Messaging
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/SignUpActivity.java
  app/src/main/java/com/example/dog_date/chat/ChatAdapter.java
  app/src/main/java/com/example/dog_date/chat/ChatObject.java
  app/src/main/java/com/example/dog_date/chat/MessageActivity.java
  app/src/main/res/drawable/my_msg.xml
  app/src/main/res/drawable/their_msg.xml
  app/src/main/res/layout/activity_message.xml
  app/src/main/res/layout/chat_item.xml
  app/src/main/res/values/colors.xml
Labels: code, research

#54 Upload Dog info to Firebase
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/DogProfile.java
  app/src/main/java/com/example/dog_date/DogProfilePage.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/Preference.java
  app/src/main/java/com/example/dog_date/Preference_owner.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/java/com/example/dog_date/Upload.java
  app/src/main/res/drawable/default_pfp.png
  app/src/main/res/layout/dog_profile_page.xml
  app/src/main/res/layout/doggy_profile.xml
  app/src/main/res/values/strings.xml
Labels: code

#59 fix bugs on match function
  app/src/main/java/com/example/dog_date/Match/MatchActivity.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
Labels: bug

#64 Saving and sending preferences to FB
  .idea/misc.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_15_2021_9_08_PM_[Default_Changelist]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_15_2021_9_08_PM_[Default_Changelist]1/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_15_2021_9_08_PM__Default_Changelist_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_15_2021_9_08_PM__Default_Changelist_1.xml
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/Preference.java
  app/src/main/java/com/example/dog_date/datamodel/FirebasePreferenceModel.java
  app/src/main/java/com/example/dog_date/models/PreferencesItems.java
  app/src/main/java/com/example/dog_date/viewmodels/FirebasePreferenceViewModel.java
Labels: code, mvp

#65 Chat Functions and Users
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/ChatActivity.java
  app/src/main/java/com/example/dog_date/Constants.java
  app/src/main/java/com/example/dog_date/CurrentUserActivity.java
  app/src/main/java/com/example/dog_date/DogProfile.java
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/MainActivity.java
  app/src/main/java/com/example/dog_date/Match/MatchViewHolders.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/SignUpActivity.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/java/com/example/dog_date/UsersActivity.java
  app/src/main/java/com/example/dog_date/adapters/ChatAdapter.java
  app/src/main/java/com/example/dog_date/adapters/UsersAdapter.java
  app/src/main/java/com/example/dog_date/chat/ChatAdapter.java
  app/src/main/java/com/example/dog_date/chat/ChatObject.java
  app/src/main/java/com/example/dog_date/chat/ChatViewHolders.java
  app/src/main/java/com/example/dog_date/chat/MessageActivity.java
  app/src/main/java/com/example/dog_date/firebase/ChatService.java
  app/src/main/java/com/example/dog_date/listeners/UserListener.java
  app/src/main/java/com/example/dog_date/models/ChatMessage.java
  app/src/main/java/com/example/dog_date/models/User.java
  app/src/main/java/com/example/dog_date/utilities/Constants.java
  app/src/main/java/com/example/dog_date/utilities/PreferenceManager.java
  app/src/main/res/drawable/background_chat_input.xml
  app/src/main/res/drawable/background_content_bottom.xml
  app/src/main/res/drawable/background_content_top.xml
  app/src/main/res/drawable/background_icon.xml
  app/src/main/res/drawable/background_receive_message.xml
  app/src/main/res/drawable/background_sent_message.xml
  app/src/main/res/drawable/custom_button.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_current_user.xml
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_users.xml
  app/src/main/res/layout/item_container_received_message.xml
  app/src/main/res/layout/item_container_sent_message.xml
  app/src/main/res/layout/item_container_user.xml
  app/src/main/res/layout/main_nav_drawer.xml
  app/src/main/res/layout/swipe_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: code

#71 Dog Profile Page
  .idea/misc.xml
  app/src/main/java/com/example/dog_date/DogProfilePage.java
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/Models/OnGetDataListener.java
  app/src/main/java/com/example/dog_date/OwnerProfilePage.java
  app/src/main/java/com/example/dog_date/Preference.java
  app/src/main/java/com/example/dog_date/ViewModels/DogProfileViewModel.java
  app/src/main/java/com/example/dog_date/ViewModels/OwnerProfileViewModel.java
  app/src/main/java/com/example/dog_date/datamodel/DogProfileModel.java
  app/src/main/java/com/example/dog_date/datamodel/OwnerProfileModel.java
  app/src/main/java/com/example/dog_date/viewmodels/FirebasePreferenceViewModel.java
  app/src/main/res/layout/dog_profile_page.xml
  app/src/main/res/layout/owner_profile_page.xml
Labels: code

#73 Owner profile page
  .idea/misc.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_15_2021_9_08_PM_[Default_Changelist]1/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_15_2021_9_08_PM__Default_Changelist_1.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/DogProfile.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/OwnerProfilePage.java
  app/src/main/java/com/example/dog_date/Upload.java
  app/src/main/java/com/example/dog_date/models/OwnerProfileModel.java
  app/src/main/res/layout/dog_profile.xml
  app/src/main/res/layout/owner_profile.xml
  app/src/main/res/layout/owner_profile_page.xml
  app/src/main/res/values/strings.xml
Labels: code

#74 location service pt 1
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/dog_date/ClickProfile.java
  app/src/main/java/com/example/dog_date/DogProfilePage.java
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/OwnerProfilePage.java
  app/src/main/java/com/example/dog_date/Preference.java
  app/src/main/java/com/example/dog_date/SwipeActivity.java
  app/src/main/java/com/example/dog_date/Upload.java
  app/src/main/java/com/example/dog_date/ViewModels/OwnerProfileViewModel.java
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/click_owner.xml
  app/src/main/res/layout/owner_profile.xml
  app/src/main/res/values/strings.xml
Labels: code

#79 Build Fixes
  app/build.gradle
  app/src/androidTest/java/com/example/dog_date/LogInActivityTest.java
  app/src/androidTest/java/com/example/dog_date/MainActivityTest.java
  app/src/androidTest/java/com/example/dog_date/OwnerProfileTest.java
  app/src/androidTest/java/com/example/dog_date/SignUpActivityTest.java
  app/src/main/java/com/example/dog_date/ClickProfile.java
  app/src/main/java/com/example/dog_date/LogInActivity.java
  app/src/main/java/com/example/dog_date/Match/MatchActivity.java
  app/src/main/java/com/example/dog_date/Models/OnGetDataListener.java
  app/src/main/java/com/example/dog_date/OwnerProfile.java
  app/src/main/java/com/example/dog_date/OwnerProfilePage.java
  app/src/main/java/com/example/dog_date/Preference.java
  app/src/main/java/com/example/dog_date/Preference_owner.java
  app/src/main/java/com/example/dog_date/Upload.java
  app/src/main/java/com/example/dog_date/UsersActivity.java
  app/src/main/java/com/example/dog_date/ViewModels/DogProfileViewModel.java
  app/src/main/java/com/example/dog_date/ViewModels/FirebasePreferenceViewModel.java
  app/src/main/java/com/example/dog_date/ViewModels/OwnerPreferenceViewModel.java
  app/src/main/java/com/example/dog_date/ViewModels/OwnerProfileViewModel.java
  app/src/main/java/com/example/dog_date/models/DogProfileModel.java
  app/src/main/java/com/example/dog_date/models/FirebasePreferenceModel.java
  app/src/main/java/com/example/dog_date/models/OwnerPreferenceItems.java
  app/src/main/java/com/example/dog_date/models/OwnerProfileModel.java
  app/src/main/java/com/example/dog_date/models/PreferencesItems.java
  app/src/main/res/layout/owner_profile.xml
  app/src/main/res/values/strings.xml
Labels: bug, code, testing

#80 fix bug
  app/src/main/java/com/example/dog_date/Upload.java
Labels: bug
